#!/bin/sh

case $BLOCK_BUTTON in
	1) $TERMINAL -e nmtui ;;
	3) pgrep -x dunst >/dev/null && notify-send "🌐 Internet module" "\- Click to connect
📡: no wifi connection
📶: wifi connection with quality
❎: no ethernet
🌐: ethernet working
" ;;
esac

[ "$(cat /sys/class/net/w*/operstate)" = 'down' ] && wifiicon="📡"

quality=$(iwlist wlp1s0 scanning | sed -e'5!d' -n -e 's/[^=]*\=//p' | cut -c 1,2)
"quality=$quality*100/70"
EESID=$(iwlist wlp1s0 scanning | sed -e'7!d' -n -e 's/[^"]*\"//p')
EESID=${EESID%?}
[ -z "${wifiicon+var}" ] && wifiicon="📶 $EESID: ${quality}%"


printf "%s %s" "$wifiicon" "$(cat /sys/class/net/e*/operstate | sed "s/down/❎/;s/up/🌐/")"
