#!/bin/sh

# This is a compilation handler, so to speak, which I have vim run.
#
# It compiles a document to pdf
#
# Uses pdflatex for tex files (if you find the pdf result kind
# of shitty, you can change it to xelatex)

file=$(basename "$1")
ext="${file##*.}"
base="${file%.*}"
command="pdflatex"

textype(){ \
	cp ~/.config/uni.bib ./
	$command "$base";
	biber "$base";
	$command "$base"
	}

case "$ext" in
	rmd) echo "require(rmarkdown); render('$file')" | R --vanilla ;;
	tex) textype "$file" ;;
	md) pandoc "$file" --pdf-engine=pdflatex -o "$base".pdf ;;
esac
