#!/bin/bash
# This basic script make pushing on git more easier


echo  "Are you in the right git repo you want to push in?"
select yn in "Yes" "No"; do
	case $yn in
	Yes ) 
read -p "Which files do you want to add to git ?  " fadd
read -p "What is your commit message ?  " mess
git add -u
if [ "$fadd" != "" ]
then
	git add $fadd
fi
git commit -m "$mess"
git push
exit
;;
	No  ) 
echo "then go there first ;)" 
exit;;
  	esac
done 
